name: Sync Team Development to Company

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  sync-company:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Team Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Company Repository
        env:
          COMPANY_PAT: ${{ secrets.COMPANY_PAT }}
        run: |
          git remote add company https://x-access-token:${COMPANY_PAT}@github.com/AnushkaTakawale/DevOps-Task6-Company.git
      - name: Fetch Company Repository
        run: |
          git fetch company

      - name: Rebase with Company Development
        run: |
          git checkout development
          git pull company development --rebase || true

      - name: Push Development to Company
        run: |
          git push company development:development --force